
services:
  api:
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile.dev
    container_name: nest_api_dev
    ports:
      - "${PORT:-3000}:3000"
    env_file: ../.env.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - node_modules_dev:/app/node_modules

    depends_on:
       mongo-dev:
         condition: service_healthy
    profiles: [ "dev" ]

  mongo:
    image: mongo:6
    container_name: mongo_dev
    restart: unless-stopped
    env_file: ../.env.dev
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data_dev:/data/db

volumes:
  mongo_data_dev:
